name: Terraform Feature Branch

on:
  push:
    branches:
      -  features/newrg2

  workflow_dispatch:

jobs:
  terraform:
    name: Terraform Init Plan
    runs-on: ubuntu-latest

    steps:

      # Checkout Feature Branch Code
      - name: Checkout Code
        uses: actions/checkout@v4


      # Azure Login
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "67f7550c-fb11-4701-a2d6-b97720977e0e",
              "clientSecret": "5jd8Q~LCu3pW_WpKQfpUBk2frSKTlzim5xqCLatU",
              "subscriptionId": "9b1848cc-ec7e-409d-862b-1c4636d199d1",
              "tenantId": "550c077a-49e3-4a1e-8c5d-4b7a327b8240"
            }


      # Install Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3


      # Check Terraform Version
      - name: Terraform Version
        run: terraform version


      # Terraform Init
      - name: Terraform Init
        run: terraform init


      # Terraform Format
      - name: Terraform Format Check
        run: terraform fmt -check


      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate


      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan